language: node_js
sudo: required
node_js:
  - 8.2.1
before-script:
  - yarn add vuepress@0.8.4
deploy:
  skip-cleanup: true
  provider: script
  script: bash ./scripts/deploy.sh
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
# cache:
#   directories:
#     - "node_modules"
